scss_files: 'app/styles/*.css.scss'

linters:
  BorderZero:
    enabled: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: 'tab'
    width: 1

  LeadingZero:
    style: include_zero

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: false

  Shorthand:
    enabled: true
    allowed_shorthands: [1,2,4]